### PR TITLE
Fixing Invalid version error and make CommonJS/AMD Compliant

### PR DESCRIPTION
**Pull request by trickeyone**
When installing via npm, kept getting

Invalid version: "0.6.beta"

### CODE REVIEW

**Comment by trickeyone** [comment]
Made CommonJS compliant
Rebuilt to include CommonJS compliancy

**Comment by trickeyone** [comment]
Fixed some scoping issues that caused tests to fail (namely rangy for the polyfills_test)

**Comment by trickeyone** [comment]
Adding CommonJS support for parser_rules

**Comment by pulges** [comment]
Added the version fix. The commonJS/AMD headers I did consider previously, but it was decided eventually, that it is better to keep the library without all these headers. For starter they will soon be replaced with the ES6 module pattern that has a fixed spec already, and secondly these headers cause a lot of problems and inflexibility when bundling code server side with various bundlers. On the other side if wysihtml and rangy need to be scoped it would be easy to just concatenate the needed parts and add a wrapper around.

    (function() {
        // all the concatenate code ....
        MyModule.wysihtml = wysihtml;
        MyModule.rangy = rangy; // If you actually need to get rangy from outside
    })();

**Pull request closed without merging**
